FROM ubuntu:22.04

ARG TOOLS_PATH=/opt/gcc-arm-none-eabi
ARG ARM_VERSION=12.2.rel1

# Prep basic packages
RUN apt update && apt-get clean && apt-get install -y \
	build-essential gcc-arm-none-eabi binutils-arm-none-eabi \
	cmake ninja-build \
	git \
	stlink-tools

ADD build.sh /usr/local/bin/build.sh
ENTRYPOINT ["/usr/local/bin/build.sh"]
