name: Purge Container Registry

on:
  workflow_dispatch:  # Allow manual triggering

jobs:
  purge:
    name: Delete untagged images
    runs-on: ubuntu-latest
    steps:
      - name: Prune container images
        uses: vlaurin/action-ghcr-prune@v0.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: ${{ github.actor }}
          container: stm32-builder
          dry-run: false
          keep-younger-than: 1
          keep-last: 0
          prune-untagged: true
          
      - name: Job summary
        run: echo "✅ Container images have been pruned according to retention policy"
